name: dnabind
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13
  - numpy=2.3
  - scipy=1.15
  - pandas=2.3
  - scikit-learn=1.7
  - matplotlib=3.10
  - numexpr
  - bottleneck
  - pyyaml
  - requests
  - jupyterlab
  - notebook
  - ipykernel
